task:
  name: Go1
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:49,${...num_envs}}
    envSpacing: 4.0
    clipObservations: 5.0
    clipActions: 1.0
    controlFrequencyInv: 2
    baseInitState:
      pos:
      - 0.0
      - 0.0
      - 0.62
      rot:
      - 0.0
      - 0.0
      - 0.0
      - 1.0
      vLinear:
      - 0.0
      - 0.0
      - 0.0
      vAngular:
      - 0.0
      - 0.0
      - 0.0
    randomCommandVelocityRanges:
      linear_x:
      - -2.0
      - 2.0
      linear_y:
      - -1.0
      - 1.0
      yaw:
      - -1.0
      - 1.0
    control:
      stiffness: 85.0
      damping: 2.0
      actionScale: 13.5
    defaultJointAngles:
      FL_hip_joint: 0.0
      FR_hip_joint: 0.0
      RL_hip_joint: 0.0
      RR_hip_joint: 0.0
      FL_thigh_joint: 0.2
      FR_thigh_joint: 0.2
      RL_thigh_joint: 0.2
      RR_thigh_joint: 0.2
      FL_calf_joint: -0.8
      FR_calf_joint: 0.8
      RL_calf_joint: -0.8
      RR_calf_joint: 0.8
    learn:
      linearVelocityXYRewardScale: 1.0
      angularVelocityZRewardScale: 0.5
      linearVelocityZRewardScale: -0.03
      jointAccRewardScale: -0.0003
      actionRateRewardScale: -0.006
      cosmeticRewardScale: -0.06
      linearVelocityScale: 2.0
      angularVelocityScale: 0.25
      dofPositionScale: 1.0
      dofVelocityScale: 0.05
      episodeLength_s: 50
  sim:
    dt: 0.01
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    add_ground_plane: true
    use_flatcache: true
    enable_scene_query_support: false
    disable_contact_processing: false
    enable_cameras: false
    default_physics_material:
      static_friction: 1.0
      dynamic_friction: 1.0
      restitution: 0.0
    physx:
      worker_thread_count: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${eq:${....sim_device},"gpu"}
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 1
      contact_offset: 0.02
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      friction_offset_threshold: 0.04
      friction_correlation_distance: 0.025
      enable_sleeping: true
      enable_stabilization: true
      max_depenetration_velocity: 100.0
      gpu_max_rigid_contact_count: 524288
      gpu_max_rigid_patch_count: 163840
      gpu_found_lost_pairs_capacity: 4194304
      gpu_found_lost_aggregate_pairs_capacity: 33554432
      gpu_total_aggregate_pairs_capacity: 4194304
      gpu_max_soft_body_contacts: 1048576
      gpu_max_particle_contacts: 1048576
      gpu_heap_capacity: 134217728
      gpu_temp_buffer_capacity: 33554432
      gpu_max_num_partitions: 8
    Anymal:
      override_usd_defaults: false
      enable_self_collisions: false
      enable_gyroscopic_forces: true
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 1
      sleep_threshold: 0.005
      stabilization_threshold: 0.001
      density: -1
      max_depenetration_velocity: 100.0
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0.0
          fixed_sigma: true
      mlp:
        units:
        - 256
        - 128
        - 64
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:Anymal,${....experiment}}
      full_experiment_name: ${.name}
      device: ${....rl_device}
      device_name: ${....rl_device}
      env_name: rlgpu
      multi_gpu: ${....multi_gpu}
      ppo: true
      mixed_precision: true
      normalize_input: true
      normalize_value: true
      value_bootstrap: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 1.0
      normalize_advantage: true
      gamma: 0.99
      tau: 0.95
      e_clip: 0.2
      entropy_coef: 0.0
      learning_rate: 0.0003
      lr_schedule: adaptive
      kl_threshold: 0.008
      truncate_grads: true
      grad_norm: 1.0
      horizon_length: 24
      minibatch_size: 24
      mini_epochs: 5
      critic_coef: 2
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.001
      max_epochs: ${resolve_default:1000,${....max_iterations}}
      save_best_after: 200
      score_to_win: 20000
      save_frequency: 50
      print_stats: true
task_name: ${task.name}
experiment: ''
num_envs: ''
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: gpu
device_id: 0
rl_device: cuda:0
multi_gpu: false
num_threads: 4
solver_type: 1
test: false
checkpoint: ''
headless: false
enable_livestream: false
mt_timeout: 30
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: omniisaacgymenvs
